name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install xmake
      run: bash <(curl -fsSL https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh)
    - name: install LCUI
      run: |
        wget https://github.com/lc-soft/LCUI/archive/develop.zip -O LCUI-develop.zip
        unzip LCUI-develop.zip
        rm LCUI-develop.zip
        cd LCUI-develop
        sh ./autogen.sh
        ./configure
        make
        sudo make install
    - name: make
      run: |
        xmake config -m coverage
        xmake -v
    - name: test
      run: xmake run test
    - name: upload coverage report
      run: coveralls --gcov-options '\-lp'
